name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Android APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: stable
          repository_root: .
          title: E-Motors
          package_name: emotorpro
          package_domain: org.bastler
          source_dir: .
          source_include_exts: py,png,kv
          requirements: python3,kivy,requests,plyer
          orientation: portrait
          osx_kivy_version: 2.1.0
          android_api: 33
          android_minapi: 24
          android_sdk: 33
          android_ndk: 25.2.9519653
          android_private_storage: True
          android_permissions: INTERNET,VIBRATE
          icon_filename: logo.png
